local-src:
	opam install --deps-only .

local-opam:
	opam install opam-playground/conf-python-3.distro

download-z3:
	cd opam-playground/z3.4.13.0 && wget https://github.com/Z3Prover/z3/archive/refs/tags/z3-4.13.0.tar.gz